# Generated by Django 6.0.7 on 2026-08-02 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Komoditas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_komoditas', models.CharField(max_length=100)),
                ('kategori', models.CharField(choices=[('Sembako', 'Sembako'), ('Bumbu', 'Bumbu Dapur'), ('Daging', 'Daging & Unggas'), ('Sayur', 'Sayur-Mayur')], max_length=50)),
                ('satuan', models.CharField(help_text='Contoh: Kg, Liter, Ikat', max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='komoditas/')),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Komoditas',
            },
        ),
    ]
