# Generated by Django 6.0.7 on 2026-08-02 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PesanKontak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subjek', models.CharField(max_length=150)),
                ('pesan', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sudah_dibaca', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Pesan Kontak',
            },
        ),
    ]
