# Generated by Django 6.1.1 on 2026-09-09 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('komoditas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='komoditas',
            name='kategori',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Kategori'),
        ),
    ]

