# Generated by Django 6.0.7 on 2026-08-04 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_kontak_rename_nama_komoditas_nama_komoditas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='berita',
            name='penulis',
        ),
        migrations.DeleteModel(
            name='Kontak',
        ),
        migrations.RenameField(
            model_name='komoditas',
            old_name='nama_komoditas',
            new_name='nama',
        ),
        migrations.RemoveField(
            model_name='komoditas',
            name='kategori',
        ),
        migrations.AddField(
            model_name='komoditas',
            name='keterangan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Berita',
        ),
    ]
