# Generated by Django 6.0.7 on 2026-08-05 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_berita_penulis_delete_kontak_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Berita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('ringkasan', models.TextField(help_text='Ringkasan singkat berita')),
                ('konten', models.TextField()),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='berita/')),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True)),
                ('penulis', models.CharField(default='Admin DKUPP', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Berita',
                'ordering': ['-tanggal_dibuat'],
            },
        ),
    ]
