# Generated by Django 6.0.7 on 2026-08-06 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_berita_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='berita',
            name='konten',
        ),
        migrations.AddField(
            model_name='berita',
            name='url_sumber',
            field=models.URLField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
