# Generated by Django 6.0.7 on 2026-08-12 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_berita_konten_berita_url_sumber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='berita',
            options={'verbose_name_plural': 'Berita'},
        ),
        migrations.AddField(
            model_name='hargakomoditas',
            name='pasar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
