# Generated by Django 6.0.7 on 2026-08-18 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_berita_options_hargakomoditas_pasar'),
    ]

    operations = [
        migrations.CreateModel(
            name='PesanKontak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('telepon', models.CharField(blank=True, max_length=20, null=True)),
                ('subjek', models.CharField(max_length=200)),
                ('pesan', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Pesan Kontak',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='berita',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Berita'},
        ),
    ]
