# Generated by Django 6.1.1 on 2026-09-08 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_pesankontak_options_alter_hargakomoditas_harga_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='Berita',
                ),
                migrations.AlterUniqueTogether(
                    name='hargakomoditas',
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name='hargakomoditas',
                    name='diinput_oleh',
                ),
                migrations.RemoveField(
                    model_name='hargakomoditas',
                    name='komoditas',
                ),
                migrations.RemoveField(
                    model_name='hargakomoditas',
                    name='pasar',
                ),
                migrations.DeleteModel(
                    name='PesanKontak',
                ),
                migrations.AlterModelTable(
                    name='pasar',
                    table='accounts_pasar',
                ),
                migrations.AlterModelTable(
                    name='profiladmin',
                    table='accounts_profiladmin',
                ),
                migrations.DeleteModel(
                    name='Komoditas',
                ),
                migrations.DeleteModel(
                    name='HargaKomoditas',
                ),
            ],
            database_operations=[]
        ),
    ]
