# Generated by Django 6.0.7 on 2026-08-03 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Komoditas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('satuan', models.CharField(default='kg', max_length=20)),
                ('keterangan', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Komoditas',
            },
        ),
        migrations.CreateModel(
            name='HargaKomoditas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('harga', models.DecimalField(decimal_places=2, max_digits=12)),
                ('komoditas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harga_set', to='accounts.komoditas')),
            ],
            options={
                'verbose_name_plural': 'Harga Komoditas',
                'ordering': ['-tanggal'],
            },
        ),
    ]
