# Generated by Django 6.0.7 on 2026-08-06 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_berita'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='berita',
            options={},
        ),
        migrations.RenameField(
            model_name='berita',
            old_name='tanggal_dibuat',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='berita',
            name='gambar',
        ),
        migrations.RemoveField(
            model_name='berita',
            name='penulis',
        ),
        migrations.AddField(
            model_name='berita',
            name='gambar_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='berita',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='berita',
            name='ringkasan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
