# Generated by Django 6.0.7 on 2026-08-24 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_pesankontak_alter_berita_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pesankontak',
            options={},
        ),
        migrations.AlterField(
            model_name='pesankontak',
            name='nama',
            field=models.CharField(max_length=100),
        ),
    ]
