# Generated by Django 6.0.7 on 2026-08-26 01:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_pesankontak_options_alter_pesankontak_nama'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pasar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pasar', models.CharField(max_length=100)),
                ('lokasi', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Pasar',
            },
        ),
        migrations.AlterModelOptions(
            name='pesankontak',
            options={'verbose_name_plural': 'Pesan Kontak'},
        ),
        migrations.AddField(
            model_name='hargakomoditas',
            name='diinput_oleh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hargakomoditas',
            name='nama_pasar_lama',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hargakomoditas',
            name='pasar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='harga_komoditas_set', to='accounts.pasar'),
        ),
        migrations.CreateModel(
            name='ProfilAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pasar', models.ForeignKey(blank=True, help_text='Kosongkan jika user adalah Admin Utama / Superuser', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.pasar')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_admin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Profil Admin Pasar',
            },
        ),
    ]
