# Generated by Django 6.1.1 on 2026-09-08 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_hargakomoditas_nama_pasar_lama_alter_hargakomoditas_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pesankontak',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Pesan Kontak'},
        ),
        migrations.AlterField(
            model_name='hargakomoditas',
            name='harga',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='komoditas',
            name='nama',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
