# Generated by Django 6.0.7 on 2026-08-02 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('komoditas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HargaHarian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wilayah', models.CharField(help_text='Nama Kabupaten/Kecamatan/Pasar', max_length=100)),
                ('latitude', models.FloatField(help_text='Koordinat Latitude untuk Peta Leaflet.js')),
                ('longitude', models.FloatField(help_text='Koordinat Longitude untuk Peta Leaflet.js')),
                ('harga', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tanggal', models.DateField()),
                ('komoditas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daftar_harga', to='komoditas.komoditas')),
            ],
            options={
                'verbose_name_plural': 'Harga Harian',
                'ordering': ['-tanggal'],
            },
        ),
    ]
