# Generated by Django 6.1.1 on 2026-09-08 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='berita',
            name='gambar_file',
            field=models.ImageField(blank=True, null=True, upload_to='berita/'),
        ),
        migrations.AlterField(
            model_name='berita',
            name='url_sumber',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
